name: Check package-lock for compromised dependencies

on:
  workflow_call:
    inputs:
      rules_url:
        required: true
        type: string

jobs:
  check-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run package-lock check
        uses: staafl/javascript-check-dependencies-action@master
        with:
          rules_url: ${{ inputs.rules_url }}