name: Check package-lock for compromised dependencies

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  check-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Use Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20

#      - name: Install dependencies for custom action
#        run: |
#          npm install

      - name: Run package-lock check
        uses: staafl/javascript-check-dependencies-action@0.0.1
        with:
          rules_url: https://raw.githubusercontent.com/staafl/javascript-check-dependencies-action/refs/heads/master/bad_deps.json